spring:
  batch:
    initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ngh@2019
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect